### ISSUE TITLE
Add domain selecting box to service search page in View Of Language Grid menu.

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#11]
In addition, update contents of service type box according to the selection of domain selecting box.

**Comment by takawitter** [comment]
In addition, update contents of service type box according to the selection of domain selecting box.

**Comment by takawitter** [comment]
This defect affects both langrid and open langrid.
So please use sources on sourceforge.

**Comment by trangmx** [comment]
My plan for modification:
- Add a DomainDropDownChoice to ServiceSearchFormPanel
- Add "onchange" event to the DomainDropDownChoice:
  + Update contents of service type box by using getAllList(domainID).

**Comment by takawitter** [comment]
The plan is fine.
Please go ahead :)

**Comment by trangmx** [comment]
I committed my modification to Git.
I already merged with source codes from sourceforge.

**Comment by takawitter** [comment]
Thanks. Please commit to sourceforge.
Do you have the right to commit to sourceforge?

**Comment by trangmx** [comment]
I think i do not have right to commit to sourcefore.
Could you add me to the project so that i can commit?
my sourceforge account is: trangmx.

**Comment by takawitter** [comment]
I add you to developers of sourceforge.
Please create a branch 20150312-add-DomainDropDownChoice under the
service-grid-server/branches from service-grid-server-trunk, check out it,
apply your modification to it and commit.

**Comment by trangmx** [comment]
I committed my modification to the 20150312-add-DomainDropDownChoice branch on sourceforge.

**Comment by takawitter** [comment]
Don't reformat the codes. It makes code checking a terrible task.

**Comment by takawitter** [comment]
The compiler level of langauge grid is 6. You seems to be using 8. Please change settings.

**Comment by takawitter** [comment]
I found two bugs.

1. We can't choose Machine Translation on service serch panel. Or at initial state, service type box may have no choice (or just indicationg "select domain").
2. We can't see domains other than Natural Language Processing(nict.nlp). The xjulangrid must be also listed because Kyoto Langrid is connecting to Urumqi Langrid.

**Comment by trangmx** [comment]
>> We can't see domains other than Natural Language Processing(nict.nlp). The xjulangrid must be also listed because Kyoto Langrid is connecting to Urumqi Langrid.
- In this case do we need to load all domains from different operation centers which are in federation connection? Do we have a function to load all domains from different operation centers?

**Comment by takawitter** [comment]
We need to load domains whose owner is connected from our grid.
We don't have the function which load directory this relation, but you can get this relation by checking Federation and Domain table.

**Comment by trangmx** [comment]
I see a function named getAllList() on DomainService which uses listAllDomains() on DomainLogic. I wonder whether we can use this function.

**Comment by takawitter** [comment]
I don't think DomainService.getAllList is suitable because it simply lists all existing domains.
We have to take account of federation relation.

**Comment by trangmx** [comment]
I am not so clear about relation between domain table and federation table. Does ownerusergridid take value from sourcegridid?

**Comment by takawitter** [comment]
Here is the pseudo code
~~~sql
select *
from Federation f, Domain d
where f.sourceGridId = selfGridId and d.ownerUserGridId = f.targetGridId;
~~~

**Comment by trangmx** [comment]
I guess there should be some conditions of f.connected and f.requesting? f.connected = true?

**Comment by takawitter** [comment]
You're right, connected = true, requesting = false

**Comment by trangmx** [comment]
I modified and committed the code, could you check it?

**Comment by takawitter** [comment]
I checked your commit.
Related domains are listed. Please add domains of self grid.
And actual search didn't work well (i.e. When searching Machine Translation of urumqi, service manager returns both Translation on Kyoto and Machine Translation on Urumuqi)

**Comment by trangmx** [comment]
Could you send me a test database? Currently I test on my local language grid which does not have information about federation.

**Comment by takawitter** [comment]
You can use /home/nakaguchi/langrid-2.0.9-20150302-030001.dump at pigeon.
Be sure turn requesting on and connected off of federation element before launching local langrid.
jp.go.nict.langrid.webapps.langrid-core-withoutp2p project is recommended because that has no p2p module on its deployment assembly.

**Comment by trangmx** [comment]
Thank you very much!
I updated the code. Could you check again?

**Comment by takawitter** [comment]
Great! Almost there.
When I search nict.nlp:Translation, services in Kyoto Open Language Grid are not appeared.
There are some services that has service type nict.nlp:Translation and they must be listed.

**Comment by trangmx** [comment]
I committed my latest modification. Could you check it?

**Comment by takawitter** [comment]
It worked fine in my local environment!
Please cleanup codes (e.g. erase commented-out codes).
Future steps.

1. My checking after cleanup.
2. Merge to trunk and test by you.
3. Test by me.
4. done.

After this issue, I plan to start mirroring main codes of service grid between github and sourceforge
(I already add git repository to sourceforge).

**Comment by trangmx** [comment]
I cleanup and committed the codes.

**Comment by takawitter** [comment]
Thanks!
I checked and found no problems.
Please merge to trunk and do test.

**Comment by trangmx** [comment]
I merged to trunk and did the test, it works fine in my local environment.

**Comment by takawitter** [comment]
Works for me including ipaddress ignoring in openlangrid mode!
Please deploy it to Kyoto Open Language Grid.

**Comment by trangmx** [comment]
I deployed the latest code to Kyoto Open Language Grid.
