### ISSUE TITLE
Moving repository from sourceforge/svn to github and sourceforge/git.

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#13]
1. Update openlangrid/langrid to latest.
1. Cleanup files and directories (i.e. remove some useless directories or files like bin, *.class and so on..)
1. Configure local git to push to both openlangrid/langrid of github and git of sourceforge servicegrid.
1. Push

**Comment by trangmx** [comment]
I committed and pushed latest source codes to both openlangrid/langrid of github and Git of sourceforge.

**Comment by takawitter** [comment]
Thanx!
