### ISSUE TITLE
Create project: org.langrid.webapps.openlangrid-core.nlp

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#17]

**Comment by trangmx** [comment]
I created project: org.langrid.webapps.openlangrid-core.nlp

**Comment by takawitter** [comment]
Did you add terms of use html?

**Comment by trangmx** [comment]
Yes I added terms of use html in WEB-INF/classes folder.

**Comment by takawitter** [comment]
I see. Thx.
