### ISSUE TITLE
複合サービスからPHPで実装された原子サービスを呼び出すと以上に時間が掛かる

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#18]

**Comment by yuu-nkjm** [comment]
https://github.com/langrid/langrid-php-library/issues/2

2015年2月(or 3月)のサービスグリッドの更新で問題は解消された様です．
再発したら，reopenします！

;; と，僕にissueをcloseする権限がなかった…

**Comment by takawitter** [comment]
ありがとうございます！(メンバーに加えました :)

**Comment by yuu-nkjm** [comment]
メンバーに加えて下さりありがとうございます！

;; 貢献ができるかは怪しいですが…
