### ISSUE TITLE
Support creating account without manager permission(e-mail notification and certification are best).

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#2]
e-mail notification and certification are best.

**Comment by takawitter** [comment]
Let's change implementation plan because we have short time.
How about ...
* dispose plan to use e-mail
* create "Create Account" page with almost same fields as user editing page.
* but this page has additional controls:
  * Term of Use information
  * Agree checkbox
  * Password and Password confirmation textbox

**Comment by langridgroup** [comment]
Dear Nakaguchi-sensei,

Yes, this way may easier and take short time to implement. I will do this.

**Comment by takawitter** [comment]
When can you start work?

**Comment by langridgroup** [comment]
Dear Nakaguchi-sensei,

Although I have to submit a paper to SCC conference, deadline on (March 1, 2015), I can spend some time to work on this. I will start working on this from today.

Best regards,

**Comment by takawitter** [comment]
I pushed my current work https://github.com/openlangrid/langrid/commit/9f9bbc34a301f3c0b699ccfe602614c04b9f4b2f .
Please continue from this (simply execute pull on feature-create-account branch.)

Why don't you use account 'tranmx' ?

**Comment by takawitter** [comment]
The role of created user from this page should be "langridserviceuser".

**Comment by trangmx** [comment]
I commit my current implementation for the user registration.
Current implementation does not consider accessright. 
to define accessright for registered user, do we need to add more field into user table in database?

**Comment by takawitter** [comment]
Wait a moment while I merge your commits to my branch.
After that, continue working on my branch(feature-newrolemodel-servicemanager).
This branch contains modification for new roles (you don't need new field on user table.
You must care new role name: 'langridserviceuser' and 'langridserviceprovider').

**Comment by takawitter** [comment]
@trangmx ,
I merged and pushed all commits to master branch.
Please move to master branch, pull commits and continue your work :)
