### ISSUE TITLE
Deploy latest langrid to Kyoto Open Langrid

### ISSUE THREAD

**Issue by takawitter** [openlangrid/langrid#8]
Deploy latest langrid to Kyoto Open Langrid.
Latest code is on sourceforge.

So the needed processes are at least followings:

1. checkout codes from sourceforge
2. make a copy of the webapp project jp.go.nict.langrid.webapps.langrid-core-p2p.nlp and name it org.langrid.webapps.openlangrid-core-p2p.nlp
3. place termofuse.html and create war file.
4. place war and unzip it to the host on which open language grid run.
5. put the setting langrid.openLangrid to context.xml of open language grid.
6. restart tomcat
7. test
    1. invoke service and check that the IP Address wasn't be recorded.
    2. test new account form.
        1. create account via new create account form.
        2. invoke service using the account.

**Comment by trangmx** [comment]
I checked out codes from sourceforge.
There is no project name jp.go.nict.langrid.webapps.langrid-core-p2p.nlp.
Do you mean jp.go.nict.langrid.webapps.langrid-core.nlp project?

**Comment by takawitter** [comment]
Yes, please use jp.go.nict.langrid.webapps.langrid-core.nlp.

**Comment by trangmx** [comment]
I finished this task:
The latest langrid is deployed on Kyoto Open Language
http://robin.ai.soc.i.kyoto-u.ac.jp/openlangrid/service_manager/

**Comment by takawitter** [comment]
Please test features added by recent works.

* Create user from new create account page.
* Open langrid doesn’t record ip address in AccessLog.

and confirm

* Basic service invocation features isn’t corrupted

**Comment by trangmx** [comment]
I tested 
  - Create user from new create account page.
  - Open langrid doesn’t record ip address in AccessLog.
These work fine.

The basis service invocation features also work fine.

**Comment by takawitter** [comment]
Please commit and push your service tests.

**Comment by trangmx** [comment]
I committed some of my service tests.
